Output images/igr.gif

Require echo

Set Shell "zsh"
Set FontSize 16
Set Width 1200
Set Height 600
Set FontFamily "Hack Nerd Font"

Type "igr"
Sleep 1000ms Enter

Type "line.invert_match(let)"
Enter
Sleep 2000ms

Type "cli"
Enter
Sleep 500ms

Type "tui"
Enter
Sleep 500ms

Ctrl+P
Type "ignore"
Sleep 1000ms
Enter
Sleep 500ms

Type "color"
Enter
Sleep 500ms

Type "upper_case()"
Enter
Sleep 1000ms

Down 1

Enter
Sleep 1000ms
